//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendOrganizationManagement.Models
{
    using Main.Dto;
    using System;
    using System.Collections.Generic;
    [CustomModel]
    public partial class @event : Main.Dto.BaseEntity
    {
        public string name { get; set; }
        public string location { get; set; }
        public string info { get; set; }
        public int done { get; set; }
        public int participant { get; set; }
        public int program_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        [Id]
        public int id { get; set; }
        [JoinColumn(Name = "program_id")]
        public virtual program program { get; set; }
    }
}
