//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendOrganizationManagement.Models
{
    using Main.Dto;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    [CustomModel]
    public partial class institution : Main.Dto.BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public institution()
        {
            this.divisions = new HashSet<division>();
            this.users = new HashSet<user>();
        }
    
       [Column]
        public string name { get; set; }
        [Column]
        public string description { get; set; }
        [Column]
        public Nullable<System.DateTime> created_date { get; set; }

        [Id]
        [Column]
        public int id { get; set; }

        [JsonIgnore]
        [ScriptIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<division> divisions { get; set; }
        [JsonIgnore]
        [ScriptIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
