//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendOrganizationManagement.Models
{
    using Main.Dto;
    using System;
    using System.Collections.Generic;
    [CustomModel]
    public partial class member : Main.Dto.BaseEntity
    {
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }

        [Id]
        public int id { get; set; }
        [JoinColumn(Name = "position_id")] 
        public virtual position position { get; set; }
    }
}
