//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendOrganizationManagement.Models
{
    using Main.Dto;
    using System;
    using System.Collections.Generic;
    [CustomModel]
    public partial class post : Main.Dto.BaseEntity
    {
        public string name { get; set; }
        public string body { get; set; }
        public Nullable<int> post_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }

        [Id]
        public int id { get; set; }

        public string title { get; set; }
        [JoinColumn(Name = "user_id")] 
        public virtual user user { get; set; }
    }
}
