//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendOrganizationManagement.Models
{
    using Main.Dto;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    [CustomModel]
    public partial class section : Main.Dto.BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public section()
        {
            this.positions = new HashSet<position>();
            this.programs = new HashSet<program>();
        }

        [Column]
        public string name { get; set; }
        [Column]
        public int division_id { get; set; }
        [Column]
        public Nullable<int> parent_section_id { get; set; }
        [Column]
        public Nullable<System.DateTime> created_date { get; set; }

        [Id]
        [Column]
        public int id { get; set; }


        [JoinColumn(Name = "division_id", Converter = "name")]
        public virtual division division { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<position> positions { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<program> programs { get; set; }
    }
}
