//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendOrganizationManagement.Models
{
    using Main.Dto;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    [CustomModel]
    public partial class user:BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.posts = new HashSet<post>();
        }

        [Column]
        public string username { get; set; }
        [Column]
        public string name { get; set; }
        [Column]
        public string password { get; set; }
        [Column]
        public string email { get; set; }
        [Column]
        public Nullable<int> admin { get; set; }
        [Column]
        public int institution_id { get; set; }
        [Column]
        public Nullable<System.DateTime> created_date { get; set; }
        [Id]
        [Column]
        public int id { get; set; }
        [JoinColumn(Name = "institution_id", Converter = "name")] 
        public virtual institution institution { get; set; }
        [JsonIgnore] 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> posts { get; set; }
    }
}
